#!/usr/bin/env bash
# Generate frontend/config.js from the deployed stack's outputs.
#
# Run after `agentcore deploy`. Reading the values from CloudFormation
# rather than copying them by hand means the page cannot drift from the
# stack it talks to.
set -euo pipefail

STACK="${1:-AgentCore-pharmaagent-default}"
REGION="${2:-ap-south-1}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

get() {
  aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
    --query "Stacks[0].Outputs[?ends_with(OutputKey, \`$1\`)].OutputValue | [0]" \
    --output text
}

CLIENT_ID="$(get UserPoolClientId)"
HOSTED_UI="$(get HostedUiDomain)"
API="$(get ApiEndpoint)"

if [[ "$CLIENT_ID" == "None" || -z "$CLIENT_ID" ]]; then
  echo "No auth outputs on $STACK." >&2
  echo "Deploy with an email domain set:" >&2
  echo "  agentcore deploy   # after setting allowedEmailDomains in agentcore/cdk/cdk.json" >&2
  exit 1
fi

cat > "$ROOT/frontend/config.js" <<EOF
// Generated by scripts/write-frontend-config.sh — do not edit.
window.APP_CONFIG = {
  clientId: '$CLIENT_ID',
  hostedUi: '$HOSTED_UI',
  apiEndpoint: '$API',
};
EOF

echo "wrote frontend/config.js"
printf '  client   %s\n  hostedUi %s\n  api      %s\n' "$CLIENT_ID" "$HOSTED_UI" "$API"
