#!/usr/bin/env bash
# Generate frontend/config.js from the deployed stack's outputs.
#
# Run after `agentcore deploy`. Reading the value from CloudFormation
# rather than copying it by hand means the page cannot drift from the
# stack it talks to.
set -euo pipefail

STACK="${1:-AgentCore-pharmaagent-default}"
REGION="${2:-ap-south-1}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

get() {
  aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
    --query "Stacks[0].Outputs[?contains(OutputKey, \`$1\`)].OutputValue | [0]" \
    --output text
}

API="$(get ApiEndpoint)"

if [[ "$API" == "None" || -z "$API" ]]; then
  echo "No API output on $STACK." >&2
  echo "Deploy first:" >&2
  echo "  agentcore deploy" >&2
  exit 1
fi

cat > "$ROOT/frontend/config.js" <<EOF
// Generated by scripts/write-frontend-config.sh — do not edit.
window.APP_CONFIG = {
  apiEndpoint: '$API',
};
EOF

echo "wrote frontend/config.js"
printf '  api %s\n' "$API"
